[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "ninja",
    "cmake>=3.12",
    "pybind11",
    "numpy",
]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"
multi_line_output = 3
